name: yt_snatcher
description: A mobile app to locally save youtube content.

publish_to: 'none'

version: 0.0.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^1.1.1
  youtube_explode_dart: ^1.6.1+2
  better_player: ^0.0.29+1
  flutter_ffmpeg: ^0.3.0
  path_provider: ^1.6.21
  video_player: ^1.0.0
  just_audio: ^0.5.6
  audio_service: ^0.15.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-Italic.ttf
          style: italic
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700